# Generated by Django 4.0.3 on 2023-03-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SahihMuslim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('artist', models.CharField(max_length=150)),
                ('audio_file', models.FileField(upload_to='')),
            ],
        ),
    ]
