# Generated by Django 4.0.3 on 2023-03-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
